-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 21:17:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cobao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cobao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cobao` DEFAULT CHARACTER SET utf8 ;
USE `cobao` ;

-- -----------------------------------------------------
-- Table `cobao`.`alergias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`alergias` (
  `IdAlergias` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreAlergia` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`IdAlergias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`datospersonales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`datospersonales` (
  `IdDatosPersonales` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `ApellidoPaterno` VARCHAR(45) NULL DEFAULT NULL,
  `ApellidoMaterno` VARCHAR(45) NULL DEFAULT NULL,
  `Curp` VARCHAR(18) NULL DEFAULT NULL,
  `Telefono` VARCHAR(45) NULL DEFAULT NULL,
  `Celular` VARCHAR(45) NULL DEFAULT NULL,
  `Correo` VARCHAR(45) NULL DEFAULT NULL,
  `Nss` VARCHAR(45) NULL DEFAULT NULL,
  `Sexo` VARCHAR(6) NULL DEFAULT NULL,
  `Foto` LONGBLOB NULL DEFAULT NULL,
  `FechaNacimiento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IdDatosPersonales`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`direccion` (
  `IdDireccion` INT(11) NOT NULL AUTO_INCREMENT,
  `Estado` VARCHAR(100) NULL DEFAULT NULL,
  `Distrito` VARCHAR(200) NULL DEFAULT NULL,
  `Municipio` VARCHAR(200) NULL DEFAULT NULL,
  `Localidad` VARCHAR(250) NULL DEFAULT NULL,
  `Colonia` VARCHAR(150) NULL DEFAULT NULL,
  `Calle` VARCHAR(200) NULL DEFAULT NULL,
  `Numero` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`IdDireccion`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`alumno` (
  `Matricula` VARCHAR(20) NOT NULL,
  `Tutor` VARCHAR(45) NULL DEFAULT NULL,
  `IdDatosPersonales` INT(11) NOT NULL,
  `IdDireccion` INT(11) NOT NULL,
  PRIMARY KEY (`Matricula`),
  INDEX `iddatospersonales_idx` (`IdDatosPersonales` ASC) VISIBLE,
  INDEX `iddireccion_idx` (`IdDireccion` ASC) VISIBLE,
  CONSTRAINT `FKIdDatosPersonales1`
    FOREIGN KEY (`IdDatosPersonales`)
    REFERENCES `cobao`.`datospersonales` (`IdDatosPersonales`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKIdDireccion1`
    FOREIGN KEY (`IdDireccion`)
    REFERENCES `cobao`.`direccion` (`IdDireccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`alumnoalergia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`alumnoalergia` (
  `IdAlumnoAlergia` INT(11) NOT NULL AUTO_INCREMENT,
  `IdAlergias` INT(11) NULL DEFAULT NULL,
  `Matricula` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`IdAlumnoAlergia`),
  INDEX `FKMatricula5_idx` (`Matricula` ASC) VISIBLE,
  INDEX `FKIdAlergias_idx` (`IdAlergias` ASC) VISIBLE,
  CONSTRAINT `FKIdAlergias`
    FOREIGN KEY (`IdAlergias`)
    REFERENCES `cobao`.`alergias` (`IdAlergias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKMatricula2`
    FOREIGN KEY (`Matricula`)
    REFERENCES `cobao`.`alumno` (`Matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`enfermedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`enfermedad` (
  `IdEnfermedad` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreEnfermedad` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`IdEnfermedad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`alumnoenfermedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`alumnoenfermedad` (
  `IdAlumnoEnfermedad` INT(11) NOT NULL AUTO_INCREMENT,
  `IdEnfermedad` INT(11) NOT NULL,
  `Matricula` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IdAlumnoEnfermedad`),
  INDEX `TIdEnfermedad_idx` (`IdEnfermedad` ASC) VISIBLE,
  INDEX `Tmatricula_idx` (`Matricula` ASC) VISIBLE,
  CONSTRAINT `FKIdEnfermedad`
    FOREIGN KEY (`IdEnfermedad`)
    REFERENCES `cobao`.`enfermedad` (`IdEnfermedad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKMatriculas3`
    FOREIGN KEY (`Matricula`)
    REFERENCES `cobao`.`alumno` (`Matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`grupo` (
  `IdGrupo` INT(11) NOT NULL,
  `NombreGrupo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdGrupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`alumnogrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`alumnogrupo` (
  `IdAlumnoGrupo` INT(11) NOT NULL AUTO_INCREMENT,
  `Matricula` VARCHAR(20) NULL DEFAULT NULL,
  `IdGrupo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdAlumnoGrupo`),
  INDEX `FkIdGrupo_idx` (`IdGrupo` ASC) VISIBLE,
  INDEX `FkMatricula9_idx` (`Matricula` ASC) VISIBLE,
  CONSTRAINT `FkIdGrupo`
    FOREIGN KEY (`IdGrupo`)
    REFERENCES `cobao`.`grupo` (`IdGrupo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FkMatricula9`
    FOREIGN KEY (`Matricula`)
    REFERENCES `cobao`.`alumno` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`materias` (
  `CodigoMaterias` INT(11) NOT NULL,
  `UAC` VARCHAR(100) NULL DEFAULT NULL,
  `HorasMaterias` INT(11) NULL DEFAULT NULL,
  `CreditosMaterias` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`CodigoMaterias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`alumnomaterias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`alumnomaterias` (
  `IdAlumnoMaterias` INT(11) NOT NULL AUTO_INCREMENT,
  `Matricula` VARCHAR(20) NOT NULL,
  `CodigoMaterias` INT(11) NOT NULL,
  PRIMARY KEY (`IdAlumnoMaterias`),
  INDEX `FKMatricula_idx` (`Matricula` ASC) VISIBLE,
  INDEX `FKCodigoMaterias_idx` (`CodigoMaterias` ASC) VISIBLE,
  CONSTRAINT `FKCodigoMaterias3`
    FOREIGN KEY (`CodigoMaterias`)
    REFERENCES `cobao`.`materias` (`CodigoMaterias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKMatricula4`
    FOREIGN KEY (`Matricula`)
    REFERENCES `cobao`.`alumno` (`Matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`semestre` (
  `IdSemestre` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreSemestre` VARCHAR(100) NULL DEFAULT NULL,
  `FechaInicio` DATE NULL DEFAULT NULL,
  `FechaFinal` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`IdSemestre`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`alumnosemestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`alumnosemestre` (
  `idAlumnoSemestre` INT(11) NOT NULL AUTO_INCREMENT,
  `Matricula` VARCHAR(20) NOT NULL,
  `idsemestre` INT(11) NOT NULL,
  PRIMARY KEY (`idAlumnoSemestre`),
  INDEX `FKMatricula_idx` (`Matricula` ASC) VISIBLE,
  INDEX `FKIdSemestre_idx` (`idsemestre` ASC) VISIBLE,
  CONSTRAINT `FKIdSemestre`
    FOREIGN KEY (`idsemestre`)
    REFERENCES `cobao`.`semestre` (`IdSemestre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKMatricula`
    FOREIGN KEY (`Matricula`)
    REFERENCES `cobao`.`alumno` (`Matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`serviciosocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`serviciosocial` (
  `IdServicioSocial` INT(11) NOT NULL AUTO_INCREMENT,
  `Dependencia` VARCHAR(200) NULL DEFAULT NULL,
  `NombreDelPrograma` VARCHAR(200) NULL DEFAULT NULL,
  `Subprograma` VARCHAR(200) NULL DEFAULT NULL,
  `ActividadBasica` VARCHAR(200) NULL DEFAULT NULL,
  `Modalidad` VARCHAR(200) NULL DEFAULT NULL,
  `Areas` VARCHAR(200) NULL DEFAULT NULL,
  `Fecha_Inicio` DATETIME NULL DEFAULT NULL,
  `Fecha_Final` DATETIME NULL DEFAULT NULL,
  `Direccion_IdDireccion` INT(11) NOT NULL,
  PRIMARY KEY (`IdServicioSocial`),
  INDEX `fk_ServicioSocial_Direccion1_idx` (`Direccion_IdDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_ServicioSocial_Direccion1`
    FOREIGN KEY (`Direccion_IdDireccion`)
    REFERENCES `cobao`.`direccion` (`IdDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`alumnoserviciosocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`alumnoserviciosocial` (
  `idAlumnoServicioSocial` INT(11) NOT NULL AUTO_INCREMENT,
  `PrimerInforme` LONGBLOB NULL DEFAULT NULL,
  `SegundoInforme` LONGBLOB NULL DEFAULT NULL,
  `TercerInforme` LONGBLOB NULL DEFAULT NULL,
  `InformeFinal` LONGBLOB NULL DEFAULT NULL,
  `Matricula` VARCHAR(20) NOT NULL,
  `IdServicioSocial` INT(11) NOT NULL,
  PRIMARY KEY (`idAlumnoServicioSocial`),
  INDEX `fkMatriculaa_idx` (`Matricula` ASC) VISIBLE,
  INDEX `fkIdServicioSocial_idx` (`IdServicioSocial` ASC) VISIBLE,
  CONSTRAINT `fkIdServicioSocial`
    FOREIGN KEY (`IdServicioSocial`)
    REFERENCES `cobao`.`serviciosocial` (`IdServicioSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkMatriculaa`
    FOREIGN KEY (`Matricula`)
    REFERENCES `cobao`.`alumno` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`calificaciones` (
  `IdCalificaciones` INT(11) NOT NULL AUTO_INCREMENT,
  `1P` FLOAT NULL DEFAULT NULL,
  `2P` FLOAT NULL DEFAULT NULL,
  `3P` FLOAT NULL DEFAULT NULL,
  `4P` FLOAT NULL DEFAULT NULL,
  `5P` FLOAT NULL DEFAULT NULL,
  `6P` FLOAT NULL DEFAULT NULL,
  `Matricula` VARCHAR(20) NOT NULL,
  `CodigoMateria` INT(11) NOT NULL,
  `PromedioGeneral` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`IdCalificaciones`),
  INDEX `Tmatricula_idx` (`Matricula` ASC) VISIBLE,
  INDEX `Tcodigo_idx` (`CodigoMateria` ASC) VISIBLE,
  CONSTRAINT `FKCodigoMateria1`
    FOREIGN KEY (`CodigoMateria`)
    REFERENCES `cobao`.`materias` (`CodigoMaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKMatricula1`
    FOREIGN KEY (`Matricula`)
    REFERENCES `cobao`.`alumno` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`cft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`cft` (
  `Id_CFT` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_CFT`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`estado` (
  `IdEstado` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreEstado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`distrito` (
  `IdDistrito` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreDistrito` VARCHAR(45) NULL DEFAULT NULL,
  `IdEstado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdDistrito`),
  INDEX `FkIdEstado_idx` (`IdEstado` ASC) VISIBLE,
  CONSTRAINT `FkIdEstado`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `cobao`.`estado` (`IdEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`profesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`profesiones` (
  `IdProfesion` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreProfesion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IdProfesion`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`docentes` (
  `Rfc` VARCHAR(20) NOT NULL,
  `IdDireccion` INT(11) NOT NULL,
  `IdDatosPersonales` INT(11) NOT NULL,
  `IdProfesion` INT(11) NOT NULL,
  PRIMARY KEY (`Rfc`),
  INDEX `Tiddireccion_idx` (`IdDireccion` ASC) VISIBLE,
  INDEX `Tiddatos_personales_idx` (`IdDatosPersonales` ASC) VISIBLE,
  INDEX `TidProfesion_idx` (`IdProfesion` ASC) VISIBLE,
  CONSTRAINT `TIdDatosPersonales2`
    FOREIGN KEY (`IdDatosPersonales`)
    REFERENCES `cobao`.`datospersonales` (`IdDatosPersonales`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `TIdDireccion1`
    FOREIGN KEY (`IdDireccion`)
    REFERENCES `cobao`.`direccion` (`IdDireccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `TIdProfesion1`
    FOREIGN KEY (`IdProfesion`)
    REFERENCES `cobao`.`profesiones` (`IdProfesion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`grupousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`grupousuario` (
  `IdGrupoUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreGrupoUsuario` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`IdGrupoUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`imparte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`imparte` (
  `Rfc` VARCHAR(20) NOT NULL,
  `CodigoMaterias` INT(11) NOT NULL,
  `IdImparte` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`IdImparte`),
  INDEX `Tcodigo_idx` (`CodigoMaterias` ASC) VISIBLE,
  INDEX `FKRfc1` (`Rfc` ASC) VISIBLE,
  CONSTRAINT `FKCodigoMaterias2`
    FOREIGN KEY (`CodigoMaterias`)
    REFERENCES `cobao`.`materias` (`CodigoMaterias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKRfc1`
    FOREIGN KEY (`Rfc`)
    REFERENCES `cobao`.`docentes` (`Rfc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`municipio` (
  `IdMunicipio` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreMunicipio` VARCHAR(45) NULL DEFAULT NULL,
  `IdDistrito` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdMunicipio`),
  INDEX `FkIdDistrito_idx` (`IdDistrito` ASC) VISIBLE,
  CONSTRAINT `FkIdDistrito`
    FOREIGN KEY (`IdDistrito`)
    REFERENCES `cobao`.`distrito` (`IdDistrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`localidad` (
  `IdLocalidad` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreLocalidad` VARCHAR(45) NULL DEFAULT NULL,
  `IdMunicipio` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdLocalidad`),
  INDEX `FkIdMunicipio_idx` (`IdMunicipio` ASC) VISIBLE,
  CONSTRAINT `FkIdMunicipio`
    FOREIGN KEY (`IdMunicipio`)
    REFERENCES `cobao`.`municipio` (`IdMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`materias_cft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`materias_cft` (
  `IdMaterias_CFT` INT(11) NOT NULL AUTO_INCREMENT,
  `CodigoMaterias` INT(11) NULL DEFAULT NULL,
  `Id_CFT` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdMaterias_CFT`),
  INDEX `FkCodigoMateriass_idx` (`CodigoMaterias` ASC) VISIBLE,
  INDEX `FkId_CFT_idx` (`Id_CFT` ASC) VISIBLE,
  CONSTRAINT `FkCodigoMateriass`
    FOREIGN KEY (`CodigoMaterias`)
    REFERENCES `cobao`.`materias` (`CodigoMaterias`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FkId_CFT`
    FOREIGN KEY (`Id_CFT`)
    REFERENCES `cobao`.`cft` (`Id_CFT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`materiasemestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`materiasemestre` (
  `IdMateriaSemestre` INT(11) NOT NULL AUTO_INCREMENT,
  `CodigoMaterias` INT(11) NOT NULL,
  `IdSemestre` INT(11) NOT NULL,
  PRIMARY KEY (`IdMateriaSemestre`),
  INDEX `FKCodigoMateria_idx` (`CodigoMaterias` ASC) VISIBLE,
  INDEX `FKIdSemestree_idx` (`IdSemestre` ASC) VISIBLE,
  CONSTRAINT `FKCodigoMateria3`
    FOREIGN KEY (`CodigoMaterias`)
    REFERENCES `cobao`.`materias` (`CodigoMaterias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKIdSemestre2`
    FOREIGN KEY (`IdSemestre`)
    REFERENCES `cobao`.`semestre` (`IdSemestre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 79
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cobao`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cobao`.`usuarios` (
  `IdUsuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `Contraseña` BLOB NOT NULL,
  `IdGrupoUsuario` INT(11) NOT NULL,
  `IdDatosPersonales` INT(11) NOT NULL,
  PRIMARY KEY (`IdUsuarios`),
  INDEX `grupo_usuario_idx` (`IdGrupoUsuario` ASC) VISIBLE,
  INDEX `Tiddatos_personales_idx` (`IdDatosPersonales` ASC) VISIBLE,
  CONSTRAINT `FKIdDatosPersonales3`
    FOREIGN KEY (`IdDatosPersonales`)
    REFERENCES `cobao`.`datospersonales` (`IdDatosPersonales`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKIdGrupoUsuario1`
    FOREIGN KEY (`IdGrupoUsuario`)
    REFERENCES `cobao`.`grupousuario` (`IdGrupoUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
